#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade not found on Thu Mar 26 14:15:28 2026
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((800, 600))
        self.SetTitle(_("frame"))

        # Menu Bar
        self.frame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.ID_OPEN, _("&Open"), _("Open an existing document"))
        wxglade_tmp_menu.Append(wx.ID_CLOSE, _("&Close file"), _("Close current document"))
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(wx.ID_EXIT, _("E&xit"), _("Finish program"))
        self.frame_menubar.Append(wxglade_tmp_menu, _("&File"))
        wxglade_tmp_menu = wx.Menu()
        self.frame_menubar.mn_Unix = wxglade_tmp_menu.Append(wx.ID_ANY, _("Unix"), _("Use Unix line endings"), wx.ITEM_RADIO)
        self.Bind(wx.EVT_MENU, self.onSelectUnix, self.frame_menubar.mn_Unix)
        self.frame_menubar.mn_Windows = wxglade_tmp_menu.Append(wx.ID_ANY, _("Windows"), _("Use Windows line endings"), wx.ITEM_RADIO)
        self.Bind(wx.EVT_MENU, self.onSelectWindows, self.frame_menubar.mn_Windows)
        wxglade_tmp_menu.AppendSeparator()
        self.frame_menubar.mn_RemoveTabs = wxglade_tmp_menu.Append(wx.ID_ANY, _("Remove Tabs"), _("Remove all leading tabs"), wx.ITEM_CHECK)
        self.Bind(wx.EVT_MENU, self.onRemoveTabs, self.frame_menubar.mn_RemoveTabs)
        self.frame_menubar.Append(wxglade_tmp_menu, _("&Edit"))
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.ID_HELP, _("Manual"), _("Show the application manual"))
        self.Bind(wx.EVT_MENU, self.onShowManual, id=wx.ID_HELP)
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(wx.ID_ABOUT, _("About"), _("Show the About dialog"))
        self.frame_menubar.Append(wxglade_tmp_menu, _("&Help"))
        self.SetMenuBar(self.frame_menubar)
        # Menu Bar end

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)

        self.thumbnail = wx.ScrolledWindow(self.panel_1, wx.ID_ANY, style=wx.BORDER_SIMPLE)
        self.thumbnail.SetMinSize((100, 600))
        self.thumbnail.SetScrollRate(5, 5)
        sizer_1.Add(self.thumbnail, 1, wx.ALL | wx.EXPAND, 5)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        self.image = wx.Panel(self.panel_1, wx.ID_ANY, style=wx.BORDER_SIMPLE)
        self.image.SetMinSize((700, 300))
        sizer_2.Add(self.image, 1, wx.ALL | wx.EXPAND, 5)

        self.text = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.text.SetMinSize((700, 300))
        sizer_2.Add(self.text, 0, wx.ALL | wx.EXPAND, 5)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        # end wxGlade

    def onSelectUnix(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'onSelectUnix' not implemented!")
        event.Skip()

    def onSelectWindows(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'onSelectWindows' not implemented!")
        event.Skip()

    def onRemoveTabs(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'onRemoveTabs' not implemented!")
        event.Skip()

    def onShowManual(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'onShowManual' not implemented!")
        event.Skip()

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = MyApp(0)
    app.MainLoop()
