#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade not found on Mon Mar 23 13:48:23 2026
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((800, 600))
        self.SetTitle(_(u"Reconhecimento Ótico de Caracteres"))

        # Menu Bar
        self.menuBar = wx.MenuBar()
        self.fileMenu = wx.Menu()
        self.menuBar.Append(self.fileMenu, _("Arquivo"))
        wxglade_tmp_menu = wx.Menu()
        self.menuBar.Append(wxglade_tmp_menu, _("_Salvar"))
        wxglade_tmp_menu = wx.Menu()
        self.menuBar.Append(wxglade_tmp_menu, _("_Sair"))
        self.editMenu = wx.Menu()
        self.menuBar.Append(self.editMenu, _("Editar"))
        self.viewMenu = wx.Menu()
        self.menuBar.Append(self.viewMenu, _("Exibir"))
        self.helpMenu = wx.Menu()
        self.menuBar.Append(self.helpMenu, _("Ajuda"))
        self.SetMenuBar(self.menuBar)
        # Menu Bar end

        sizer = wx.BoxSizer(wx.VERTICAL)

        self.panel_image = wx.Panel(self, wx.ID_ANY)
        sizer.Add(self.panel_image, 1, wx.ALL | wx.EXPAND, 5)

        self.txt_output = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        sizer.Add(self.txt_output, 1, wx.ALL | wx.EXPAND, 5)

        self.SetSizer(sizer)

        self.Layout()
        # end wxGlade

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = MyApp(0)
    app.MainLoop()
