#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade not found on Wed Mar 25 18:30:11 2026
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MainFrame(wx.Frame):
    def __init__(self, *args, **kw):
        # ensure the parent's __init__ is called
        super(MainFrame, self).__init__(*args, **kw)

        self.panel = wx.Panel(self, wx.ID_ANY)

        main = wx.BoxSizer(wx.VERTICAL)

        top = wx.BoxSizer(wx.HORIZONTAL)
        main.Add(top, 1, wx.EXPAND, 0)

        self.ThumbnailPanel = wx.ScrolledWindow(self.panel, wx.ID_ANY, style=wx.TAB_TRAVERSAL)
        self.ThumbnailPanel.SetScrollRate(10, 10)
        top.Add(self.ThumbnailPanel, 1, wx.ALL | wx.EXPAND, 5)

        self.AdvancedImagePanel = wx.Panel(self.panel, wx.ID_ANY)
        top.Add(self.AdvancedImagePanel, 1, wx.ALL | wx.EXPAND, 5)

        self.text_ctrl_1 = wx.TextCtrl(self.panel, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        main.Add(self.text_ctrl_1, 0, wx.EXPAND, 0)

        self.panel.SetSizer(main)

        self.Layout()
        # end wxGlade

# end of class MainFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MainFrame(None, title="Reconhecimento Ótico de Caracteres",size=(800,600), style=wx.DEFAULT_FRAME_STYLE ^ wx.RESIZE_BORDER)
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
