# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frm_youtube_downloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import os
import subprocess
import yt_dlp
from PyQt5 import QtCore, QtGui, QtWidgets as qtw

app_path = os.path.dirname(os.path.abspath(__file__))
ffmpeg = os.path.join(app_path, 'ffmpeg.exe')


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 150)

        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)

        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Youtube.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("Youtube.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)

        self.centralwidget = qtw.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.linkLabel = qtw.QLabel(self.centralwidget)
        self.linkLabel.setGeometry(QtCore.QRect(20, 10, 47, 13))
        self.linkLabel.setFont(font)
        self.linkLabel.setObjectName("linkLabel")

        self.urlText = qtw.QLineEdit(self.centralwidget)
        self.urlText.setGeometry(QtCore.QRect(20, 30, 460, 20))
        self.urlText.setObjectName("urlText")

        self.destinyLabel = qtw.QLabel(self.centralwidget)
        self.destinyLabel.setGeometry(QtCore.QRect(20, 60, 91, 16))
        self.destinyLabel.setFont(font)
        self.destinyLabel.setLineWidth(17)
        self.destinyLabel.setObjectName("destinyLabel")

        self.destinyText = qtw.QLineEdit(self.centralwidget)
        self.destinyText.setGeometry(QtCore.QRect(20, 80, 425, 20))
        self.destinyText.setObjectName("destinyText")
        self.destinyText.setText("D:\\Downloads")

        self.folderButton = qtw.QToolButton(self.centralwidget)
        self.folderButton.setGeometry(QtCore.QRect(455, 80, 25, 23))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("folder-open.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.folderButton.setIcon(icon1)
        self.folderButton.setObjectName("folderButton")

        self.downloadButton = qtw.QPushButton(self.centralwidget)
        self.downloadButton.setGeometry(QtCore.QRect(310, 115, 75, 23))
        self.downloadButton.setFont(font)
        self.downloadButton.setObjectName("downloadButton")

        self.fileTypeComboBox = qtw.QComboBox(self.centralwidget)
        self.fileTypeComboBox.setGeometry(QtCore.QRect(20, 115, 155, 23))
        self.fileTypeComboBox.setObjectName("fileTypeComboBox")
        self.fileTypeComboBox.addItem("1 - Baixar VÍDEO")
        self.fileTypeComboBox.addItem("2 - Baixar ÁUDIO (M4A)")
        self.fileTypeComboBox.addItem("3 - Baixar ÁUDIO (MP3)")

        self.apagaVideoBox = qtw.QCheckBox(self.centralwidget)
        self.apagaVideoBox.setGeometry(QtCore.QRect(190, 118, 95, 17))
        self.apagaVideoBox.setObjectName("apagaVideoBox")

        self.cancelButton = qtw.QPushButton(self.centralwidget)
        self.cancelButton.setGeometry(QtCore.QRect(405, 115, 75, 23))
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")

        # buttons
        self.folderButton.clicked.connect(self.selectDir)
        self.downloadButton.clicked.connect(self.download)
        self.cancelButton.clicked.connect(qtw.QApplication.quit)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "Youtube Downloader"))
        self.linkLabel.setText(_translate("MainWindow", "URL link:"))
        self.destinyLabel.setText(_translate(
            "MainWindow", "File Destination:"))
        self.folderButton.setText(_translate("MainWindow", "..."))
        self.downloadButton.setText(_translate("MainWindow", "Download"))
        self.apagaVideoBox.setText(_translate("MainWindow", "Apagar Vídeo"))
        self.cancelButton.setText(_translate("MainWindow", "Exit"))

    def showdialog(self, title, mensagem):
        msg = qtw.QMessageBox()
        msg.setIcon(qtw.QMessageBox.Information)

        msg.setText(mensagem)
        msg.setWindowTitle(title)
        msg.setStandardButtons(qtw.QMessageBox.Ok)
        msg.buttonClicked.connect(self.msgbtn)

        retval = msg.exec_()

    def msgbtn(self, i):
        print("Button pressed is:", i.text())

    # Seleciona local aonde arquivo será salvo
    def selectDir(self):
        selected_dir = qtw.QFileDialog.getExistingDirectory(
            MainWindow, caption='Choose Directory', directory=os.getcwd())

        if selected_dir != '':
            selected_dir = selected_dir.replace('/', '\\')
            os.rename(selected_dir, selected_dir.replace(' ', ''))
            selected_dir = selected_dir.replace(' ', '')
            self.destinyText.setText(selected_dir)

    def obtem_path(self):
        path = self.destinyText.text()
        return path

    def download(self):
        url = self.urlText.text()
        selected_text = self.fileTypeComboBox.currentText()
        selected_index = self.fileTypeComboBox.currentIndex()

        print("Selected Text: ", selected_text)
        print("Selected Item: ", selected_index)

        baixar(url, selected_text)


# Não funcionou
""" def extrair_cookies():
    # Execute o seguinte comando para baixar os cookies: yt-dlp --cookies-from-browser chrome --cookies cookies.txt

    print("🔄 Extraindo cookies do Chrome...")
    try:
        subprocess.run(
            ["yt-dlp", "--cookies-from-browser",
                "chrome", "--cookies", "cookies.txt"],
            check=True
        )
        print("✅ Cookies extraídos com sucesso!\n")
    except subprocess.CalledProcessError:
        print("❌ Falha ao extrair cookies. Abra o Chrome, faça login no YouTube e tente novamente.")
        exit(1) """


def baixar(url, opcao):
    # Sempre extrai cookies antes de baixar
    # extrair_cookies()

    # Isso funciona
    # Execute o seguinte comando para baixar os cookies: yt-dlp --cookies-from-browser chrome --cookies cookies.txt

    base_opts = {
        "cookiefile": "cookies.txt",       # <— cookies obrigatórios
        "check_formats": True,
        "retries": 10,
        "http_headers": {"User-Agent": "Mozilla/5.0"},
        "outtmpl": "%(title)s.%(ext)s",
    }

    if opcao == "1 - Baixar VÍDEO":
        print("\n🟦 Baixando VÍDEO na melhor qualidade sem DRM...\n")
        ydl_opts = {
            "format": "bv*+ba/b",
            "check_formats": True,
            "merge_output_format": "mp4",
            "outtmpl": "%(title)s.%(ext)s",
            "retries": 10,
            "http_headers": {"User-Agent": "Mozilla/5.0"},
        }

    elif opcao == "2 - Baixar ÁUDIO (M4A)":
        print("\n🟩 Baixando ÁUDIO em M4A (melhor qualidade)...\n")
        ydl_opts = {
            "format": "bestaudio/best",
            "check_formats": True,
            "postprocessors": [
                {
                    "key": "FFmpegExtractAudio",
                    "preferredcodec": "m4a",
                }
            ],
            "outtmpl": "%(title)s.%(ext)s",
        }

    elif opcao == "3 - Baixar ÁUDIO (MP3)":
        print("\n🟧 Baixando ÁUDIO em MP3...\n")
        ydl_opts = {
            "format": "bestaudio/best",
            "check_formats": True,
            "postprocessors": [
                {
                    "key": "FFmpegExtractAudio",
                    "preferredcodec": "mp3",
                    "preferredquality": "192",
                }
            ],
            "outtmpl": "%(title)s.%(ext)s",
        }

    else:
        print("❌ Opção inválida.")
        return

    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        ydl.download([url])


if __name__ == "__main__":
    app = qtw.QApplication(sys.argv)
    MainWindow = qtw.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
