# Form implementation generated from reading ui file 'frm_youtube_downloader.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 150)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.downloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.downloadButton.setGeometry(QtCore.QRect(20, 110, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.downloadButton.setFont(font)
        self.downloadButton.setObjectName("downloadButton")
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelButton.setGeometry(QtCore.QRect(405, 110, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")
        self.linkLabel = QtWidgets.QLabel(self.centralwidget)
        self.linkLabel.setGeometry(QtCore.QRect(20, 10, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.linkLabel.setFont(font)
        self.linkLabel.setObjectName("linkLabel")
        self.destinyLabel = QtWidgets.QLabel(self.centralwidget)
        self.destinyLabel.setGeometry(QtCore.QRect(20, 60, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.destinyLabel.setFont(font)
        self.destinyLabel.setLineWidth(17)
        self.destinyLabel.setObjectName("destinyLabel")
        self.urlText = QtWidgets.QLineEdit(self.centralwidget)
        self.urlText.setGeometry(QtCore.QRect(20, 30, 460, 20))
        self.urlText.setObjectName("urlText")
        self.destinyText = QtWidgets.QLineEdit(self.centralwidget)
        self.destinyText.setGeometry(QtCore.QRect(20, 80, 460, 20))
        self.destinyText.setObjectName("destinyText")
        self.audioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.audioButton.setGeometry(QtCore.QRect(290, 113, 51, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.audioButton.setFont(font)
        self.audioButton.setObjectName("audioButton")
        self.videoButton = QtWidgets.QRadioButton(self.centralwidget)
        self.videoButton.setGeometry(QtCore.QRect(150, 113, 50, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.videoButton.setFont(font)
        self.videoButton.setChecked(True)
        self.videoButton.setObjectName("videoButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Youtube Downloader"))
        self.downloadButton.setText(_translate("MainWindow", "Download"))
        self.cancelButton.setText(_translate("MainWindow", "Exit"))
        self.linkLabel.setText(_translate("MainWindow", "URL link:"))
        self.destinyLabel.setText(_translate("MainWindow", "File Destination:"))
        self.audioButton.setText(_translate("MainWindow", "Audio"))
        self.videoButton.setText(_translate("MainWindow", "Video"))
